### ISSUE TITLE
unable to destroy session

### ISSUE THREAD

**Issue by rohithramachandran** [Requarks/connect-loki#3]
when i am trying to destroy a session (`store.destroy `) with following code
route.js
   ```
   30   var store=req.sessionStore;
   31   store.destroy(sessionID, function(error){
   32      logger.info("Session destroyed");
   33      res.end();
   30  });
```

i am getting this error

```
Error: Object is not a document stored in the collection
   at LokiEventEmitter.Collection.remove (/home/rohith/workspace/express/SelfcareServer/node_modules/lokijs/src/lokijs.js:4112:15)
   at LokiStore.client.loadDatabase.LokiStore.destroy (/home/rohith/workspace/express/SelfcareServer/node_modules/connect-loki/lib/connect-loki.js:151:19)
   at /home/rohith/workspace/express/SelfcareServer/modules/routes.js:31:13
```

Can somebody help me out this problem ?

**Comment by rohithramachandran** [comment]
I was using store and accessing the session directly...When i destroyed the session with store.destroy it works .. thanks for the plugin and sorry for the issue

**Comment by IETF-Zulip** [comment]
> khi tôi đang cố gắng hủy một phiên ( `store.destroy `) bằng mã sau route.js
> 
> ```
> 30   var store=req.sessionStore;
> 31   store.destroy(sessionID, function(error){
> 32      logger.info("Session destroyed");
> 33      res.end();
> 30  });
> ```
> 
> tôi đang gặp lỗi này
> 
> ```
> Error: Object is not a document stored in the collection
>    at LokiEventEmitter.Collection.remove (/home/rohith/workspace/express/SelfcareServer/node_modules/lokijs/src/lokijs.js:4112:15)
>    at LokiStore.client.loadDatabase.LokiStore.destroy (/home/rohith/workspace/express/SelfcareServer/node_modules/connect-loki/lib/connect-loki.js:151:19)
>    at /home/rohith/workspace/express/SelfcareServer/modules/routes.js:31:13
> ```
> 
> Có ai có thể giúp tôi giải quyết vấn đề này không?
https://github.com/requarks/connect-loki/issues/3
https://github.com/requarks/connect-loki/issues/3#issue-188921901
