### ISSUE TITLE
Code Optimization. Code Refactor.

### ISSUE THREAD

**Issue by Romick2005** [Requarks/connect-loki#6]
In connect-loki/lib/connect-loki.js:
1) `Promise = require('bluebird')`//it is unused. It can be safely removed from code.
2) You use only noop and isNill from loadash. But what is the reason to load hole loadash for this simple function and also add additional dependency? noop = `function () {}` and isNill = `obj === null`.
So in package.json you can remove
```
"dependencies": {
    "bluebird": "^3.4.1",
    "lodash": "^4.15.0",
}
```
3) What is the reason always pass to the function callpack functuion as a parameter? Like:
```
	LokiStore.prototype.clear = function (fn) {
		if(!fn) { fn = _.noop; }
		this.collection.clear();
		fn(null);
	};
```
I would make it more cleaner:
```
	LokiStore.prototype.clear = function () {
		return this.collection.clear();
	};
```
Because I guess "clear" method is synchronous and you don't need callback there.
So 
`lokiStore.clear(callback) `
can be easily be rewritten to:
```
lokiStore.clear();
callback();
```

**Comment by NGPixel** [comment]
Update to v1.1.0. Unused dependencies were removed and code was refactored to StandardJS specs.

As for the callbacks, this is for compatibility reasons. Some apps expect to have a callback when calling a connect-style adapter. So even though everything is synchronous, I must provide the feature.

**Comment by IETF-Zulip** [comment]
> Trong connect-loki/lib/connect-loki.js:
> 
> 1. `Promise = require('bluebird')`//nó không được sử dụng. Nó có thể được xóa khỏi mã một cách an toàn.
> 2. Bạn chỉ sử dụng noop và isNill từ loadash. Nhưng lý do gì để tải loadash hole cho hàm đơn giản này và cũng thêm phụ thuộc bổ sung? noop = `function () {}`và isNill = `obj === null`. 
>    Vì vậy, trong package.json, bạn có thể xóa
> 
> ```
> "dependencies": {
>     "bluebird": "^3.4.1",
>     "lodash": "^4.15.0",
> }
> ```
> 
> 3. Tại sao luôn truyền hàm callpack functuion làm tham số? Giống như:
> 
> ```
> 	LokiStore.prototype.clear = function (fn) {
> 		if(!fn) { fn = _.noop; }
> 		this.collection.clear();
> 		fn(null);
> 	};
> ```
> 
> Tôi sẽ làm cho nó sạch hơn:
> 
> ```
> 	LokiStore.prototype.clear = function () {
> 		return this.collection.clear();
> 	};
> ```
> 
> Bởi vì tôi đoán phương thức "clear" là đồng bộ và bạn không cần gọi lại ở đó. Vì vậy, `lokiStore.clear(callback) ` có thể dễ dàng viết lại thành:
> 
> ```
> lokiStore.clear();
> callback();
> ```

https://github.com/requarks/connect-loki/issues/6
https://github.com/requarks/connect-loki/issues/6#issue-238877998
